name: flutter_github
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.15.8 <0.19.0"
  cupertino_icons: ">=0.1.2 <2.0.0"
  provider: ">=3.0.0+1 <7.0.0"
  json_annotation: ">=2.0.0 <5.0.0"
  dio: ">=3.0.3 <6.0.0"
  fluttertoast: ">=3.0.3 <9.0.0"
  cached_network_image: ">=0.8.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ">=0.17.4 <0.19.0"
  build_runner: ">=1.0.0 <3.0.0"
  json_serializable: ">=2.0.0 <7.0.0"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - imgs/avatar-default.png
    - imgs/logo_light.png
    - imgs/logo_dark.png


  fonts:
    - family: myIcon
      fonts:
        - asset: fonts/iconfont.ttf